### ISSUE TITLE
Deleting all vertices and edges in a graph

### ISSUE THREAD

**Issue by kaatish** [robmccoll/stinger#109]
I am trying to delete all the vertices from a graph using the following code snippet.
```
        auto maxVertex = stinger_max_active_vertex(graph);
        for (int64_t i = 0; i < maxVertex; ++i) {
            stinger_remove_vertex(graph, i);
        }
```
This gives me the following error
```stinger[20429]: stinger_names_remove_type 288: Deleting of stinger names is unsupported in base mode```

Looking at the function definitions it seems like stinger_remove_vertex is only supported when using sqlite. Is that correct? Is there any clean way to 'clear' the graph easily, that is, revert it to the state after a ```stinger_new_full``` call?

**Comment by davidediger** [comment]
There are a few things to say about this.  While STINGER has support for deleting edges and (sometimes) vertices, it's not a common thing in streaming data, so it's not perfect.  By default, when a logical vertex ID is assigned a physical ID (a string), that mapping cannot be undone.  Likewise, when edge blocks are assigned a type and a source vertex, that is permanent.

The function stinger_remove_all_edges_of_type() will remove a bunch of edges, but does not free or re-allocate edge blocks.

We recently added SQLite as an experimental way to handle mapping of strings to vertices so that you could delete mappings.  There is an order of magnitude performance penalty for doing so.  With SQLite compiled in, you still won't be able to reallocate edge blocks.

If the goal is to return the STINGER structure back to its original form, I would suggest that you free it and allocate a new one.  We would certainly accept a pull request with a stinger_reset() function and I don't think it would be that hard to write, but could be slower than free/new because of the number of pages you will have to touch.
